export const SETTINGS_DEFAULTS = {
  llmProvider: 'openai',
  scoutPipelineMinCritic: '65',
  scoutPipelineMinImdb: '7.0',
  scoutPipelineBatchSize: '5',
  scoutPipelineAutoEnabled: 'false',
  scoutPipelineAutoIntervalMin: '60',
  scoutPipelineAutoCooldownMin: '240',
  scoutPipelineBasicRes2160: '46',
  scoutPipelineBasicRes1080: '24',
  scoutPipelineBasicRes720: '8',
  scoutPipelineBasicSourceRemux: '30',
  scoutPipelineBasicSourceBluray: '20',
  scoutPipelineBasicSourceWebdl: '14',
  scoutPipelineBasicVideoHevc: '22',
  scoutPipelineBasicVideoAv1: '10',
  scoutPipelineBasicVideoH264: '8',
  scoutPipelineBasicAudioAtmos: '10',
  scoutPipelineBasicAudioTruehd: '8',
  scoutPipelineBasicAudioDts: '6',
  scoutPipelineBasicAudioDdp: '5',
  scoutPipelineBasicAudioAc3: '2',
  scoutPipelineBasicAudioAac: '1',
  scoutPipelineBitrateTargetMbps: '18',
  scoutPipelineBitrateTolerancePct: '40',
  scoutPipelineBitrateMaxScore: '12',
  scoutPipelineBasicLegacyPenalty: '40',
  scoutPipelineBasicSeedersDivisor: '25',
  scoutPipelineBasicSeedersBonusCap: '10',
  scoutPipelineBasicUsenetBonus: '10',
  scoutPipelineBasicTorrentBonus: '0',
  scoutPipelineBlockersEnabled: 'false',
  scoutPipelineLlmTieDelta: '10',
  scoutPipelineLlmWeakDropDelta: '40',
  jfSyncIntervalMin: '30',
  jfSyncBatchSize: '10',
} as const;

export type SettingsDefaultKey = keyof typeof SETTINGS_DEFAULTS;
