export const SETTINGS_DEFAULTS = {
  llmProvider: 'openai',
  scoutPipelineMinCritic: '65',
  scoutPipelineMinImdb: '7.0',
  scoutPipelineBatchSize: '5',
  scoutPipelineAutoEnabled: 'false',
  scoutPipelineAutoIntervalMin: '60',
  scoutPipelineAutoCooldownMin: '240',
  scoutPipelineBasicResolutionScore: '6',
  scoutPipelineBasicVideoScore: '5',
  scoutPipelineBasicAudioScore: '4',
  scoutPipelineBitrateTargetMbps: '18',
  scoutPipelineBitrateTolerancePct: '40',
  scoutPipelineBitrateMaxScore: '12',
  scoutPipelineTrashRes2160: '46',
  scoutPipelineTrashRes1080: '24',
  scoutPipelineTrashRes720: '8',
  scoutPipelineTrashSourceRemux: '30',
  scoutPipelineTrashSourceBluray: '20',
  scoutPipelineTrashSourceWebdl: '14',
  scoutPipelineTrashCodecHevc: '22',
  scoutPipelineTrashCodecAv1: '10',
  scoutPipelineTrashCodecH264: '8',
  scoutPipelineTrashAudioAtmos: '10',
  scoutPipelineTrashAudioTruehd: '8',
  scoutPipelineTrashAudioDts: '6',
  scoutPipelineTrashAudioDdp: '5',
  scoutPipelineTrashAudioAc3: '2',
  scoutPipelineTrashAudioAac: '1',
  scoutPipelineTrashLegacyPenalty: '40',
  scoutPipelineTrashSeedersDivisor: '25',
  scoutPipelineTrashSeedersBonusCap: '10',
  scoutPipelineTrashUsenetBonus: '10',
  scoutPipelineTrashTorrentBonus: '0',
  scoutPipelineBlockersEnabled: 'false',
  scoutPipelineLlmTieDelta: '10',
  scoutPipelineLlmWeakDropDelta: '40',
  jfSyncIntervalMin: '30',
  jfSyncBatchSize: '10',
} as const;

export type SettingsDefaultKey = keyof typeof SETTINGS_DEFAULTS;
