export const SETTINGS_DEFAULTS = {
  llmProvider: 'openai',
  scoutMinCritic: '65',
  scoutMinCommunity: '7.0',
  scoutSearchBatchSize: '5',
  scoutAutoEnabled: 'false',
  scoutAutoIntervalMin: '60',
  scoutAutoCooldownMin: '240',
  scoutCfRes2160: '46',
  scoutCfRes1080: '24',
  scoutCfRes720: '8',
  scoutCfSourceRemux: '30',
  scoutCfSourceBluray: '20',
  scoutCfSourceWebdl: '14',
  scoutCfCodecHevc: '22',
  scoutCfCodecAv1: '10',
  scoutCfCodecH264: '8',
  scoutCfAudioAtmos: '10',
  scoutCfAudioTruehd: '8',
  scoutCfAudioDts: '6',
  scoutCfAudioDdp: '5',
  scoutCfAudioAc3: '2',
  scoutCfAudioAac: '1',
  scoutCfLegacyPenalty: '40',
  scoutCfBitrateMin2160Mbps: '10',
  scoutCfBitrateMax2160Mbps: '35',
  scoutCfBitrateMin1080Mbps: '4',
  scoutCfBitrateMax1080Mbps: '15',
  scoutCfBitrateMin720Mbps: '2.5',
  scoutCfBitrateMax720Mbps: '8',
  scoutCfBitrateMinOtherMbps: '1',
  scoutCfBitrateMaxOtherMbps: '12',
  scoutCfSeedersDivisor: '25',
  scoutCfSeedersBonusCap: '10',
  scoutCfUsenetBonus: '10',
  scoutCfTorrentBonus: '0',
  jfSyncIntervalMin: '30',
  jfSyncBatchSize: '10',
} as const;

export type SettingsDefaultKey = keyof typeof SETTINGS_DEFAULTS;
